<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ClanAI</AssemblyName>
    <AssemblyVersion>0.22.0.0</AssemblyVersion>
    <FileVersion>0.22.0.0</FileVersion>
    <InformationalVersion>v0.22.0</InformationalVersion>
    <RootNamespace>ClanAI</RootNamespace>
    <BannerlordInstallDir Condition="'$(BannerlordInstallDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord</BannerlordInstallDir>
    <BannerlordBinDir Condition="'$(BannerlordBinDir)' == ''">$(BannerlordInstallDir)\bin\Win64_Shipping_Client</BannerlordBinDir>
    <BannerlordHarmonyBinDir Condition="'$(BannerlordHarmonyBinDir)' == ''">$(BannerlordInstallDir)\Modules\Bannerlord.Harmony\bin\Win64_Shipping_Client</BannerlordHarmonyBinDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="TaleWorlds.Core">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
  
    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
  
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(BannerlordBinDir)\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BannerlordHarmonyBinDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>






