using System;
using System.Reflection;
using ClanAI;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.CampaignBehaviors.AiBehaviors;
using TaleWorlds.ObjectSystem;
class Program {
 static int count;
 static void Check(bool ok,string name){if(!ok)throw new Exception(name);count++;Console.WriteLine("PASS "+name);}
 static MobileParty Actor(string id) {
 var h=new Hero{StringId=id,Clan=Clan.PlayerClan};
 var p=new MobileParty{StringId="party_"+id,LeaderHero=h,ActualClan=Clan.PlayerClan,MapFaction=Clan.PlayerClan};h.PartyBelongedTo=p;return p;
 }
 static Settlement Home(string id){return new Settlement{StringId=id,OwnerClan=Clan.PlayerClan,IsCastle=true};}
 static void Main(){
 var a=Actor("a");var b=Actor("b");var home=Home("castle_a");var second=Home("castle_b");Settlement result;
 Check(!HomeAssignmentStore.TryHome(a,out result)&&MBObjectManager.Instance.Objects.Count==0,"unassigned fast path no resolution/enumeration");
 Check(HomeAssignmentStore.Assign(a,home)&&HomeAssignmentStore.Assign(b,second),"multiple runtime assignments");
 Check(HomeAssignmentStore.TryHome(a,out result)&&ReferenceEquals(home,result),"cached direct home");
 a.Army=new object();Check(!HomeAssignmentStore.Eligible(a),"army excluded");a.Army=null;
 a.IsMainParty=true;Check(!HomeAssignmentStore.Eligible(a),"main excluded");a.IsMainParty=false;
 a.IsCaravan=true;Check(!HomeAssignmentStore.Eligible(a),"caravan excluded");a.IsCaravan=false;
 a.NavigationCapability=MobileParty.NavigationType.All;Check(HomeAssignmentStore.Eligible(a),"ship-capable party on land remains eligible");
 a.IsCurrentlyAtSea=true;Check(!HomeAssignmentStore.Eligible(a),"ship-capable party currently at sea excluded");
 a.NavigationCapability=MobileParty.NavigationType.Default;Check(!HomeAssignmentStore.Eligible(a),"current sea state excludes regardless of capability");
 a.IsCurrentlyAtSea=false;Check(HomeAssignmentStore.Eligible(a),"returning to land restores eligibility");
 a.Ai.IsDisabled=true;Check(!HomeAssignmentStore.Eligible(a),"disabled excluded");a.Ai.IsDisabled=false;
 a.Ai.DoNotMakeNewDecisions=true;Check(!HomeAssignmentStore.Eligible(a),"stopped excluded");a.Ai.DoNotMakeNewDecisions=false;
 a.IsDisbanding=true;Check(!HomeAssignmentStore.Eligible(a),"disbanding excluded");a.IsDisbanding=false;
 a.LeaderHero.Age=12;Check(!HomeAssignmentStore.Eligible(a),"child excluded");a.LeaderHero.Age=30;
 a.LeaderHero.PartyBelongedTo=null;Check(!HomeAssignmentStore.Eligible(a)&&HomeAssignmentStore.CurrentHome(a.LeaderHero)==home,"dormant hero keeps home");a.LeaderHero.PartyBelongedTo=a;
 HomeAssignmentVisitPatch.Install();
 var postfix=typeof(HomeAssignmentVisitPatch).GetMethod("Postfix",BindingFlags.NonPublic|BindingFlags.Static);
 var list=AiVisitSettlementBehavior.List();postfix.Invoke(null,new object[]{a,list});
 Check(list.Count==1&&AiVisitSettlementBehavior.Seen==home,"actual postfix exposes only exact native home");
 postfix.Invoke(null,new object[]{a,list});Check(list.Count==1,"seam does not duplicate existing home");
 AiVisitSettlementBehavior.Suitable=false;list=AiVisitSettlementBehavior.List();postfix.Invoke(null,new object[]{a,list});Check(list.Count==0,"native unsuitable/hostile refusal");AiVisitSettlementBehavior.Suitable=true;
 AiVisitSettlementBehavior.Navigation=MobileParty.NavigationType.None;postfix.Invoke(null,new object[]{a,list});Check(list.Count==0,"native navigation refusal");AiVisitSettlementBehavior.Navigation=MobileParty.NavigationType.Default;
 a.NavigationCapability=MobileParty.NavigationType.All;AiVisitSettlementBehavior.Navigation=MobileParty.NavigationType.Naval;
 postfix.Invoke(null,new object[]{a,list});Check(list.Count==0,"ship-capable land party cannot expose a naval home route");AiVisitSettlementBehavior.Navigation=MobileParty.NavigationType.Default;
 postfix.Invoke(null,new object[]{a,list});Check(list.Count==1,"ship-capable land party can expose native land home route");a.NavigationCapability=MobileParty.NavigationType.Default;
 var think=new PartyThinkParams();think.AIBehaviorScores.Add(Tuple.Create(new AIBehaviorData{Party=home,AiBehavior=AiBehavior.GoToSettlement},1f));
 think.AIBehaviorScores.Add(Tuple.Create(new AIBehaviorData{Party=second,AiBehavior=AiBehavior.GoToSettlement},1.1f));
 var frame=new StrategicDecisionComposer.Frame{CandidateCount=2,BeforeWinner=1};
 HomeAssignmentLayer.Apply(a,think,frame);
 Check(frame.CurrentBestIndex(think)==0&&think.AIBehaviorScores.Count==2&&ReferenceEquals(think.AIBehaviorScores[0].Item1.Party,home),"composer changes winner preserving count and target");
 a.DefaultBehavior=AiBehavior.GoToSettlement;a.TargetSettlement=second;
 a.ShortTermBehavior=AiBehavior.Other;a.ShortTermTargetSettlement=home;
 HomeAssignmentLayer.Apply(a,think,new StrategicDecisionComposer.Frame{CandidateCount=2,BeforeWinner=1});
 Check(HomeAssignmentCounters.CommitMismatches==1&&HomeAssignmentCounters.CommitMatches==0,"crossed behavior/target pairs do not falsely match");
 a.TargetSettlement=home;
 HomeAssignmentLayer.Apply(a,think,new StrategicDecisionComposer.Frame{CandidateCount=2,BeforeWinner=1});
 Check(HomeAssignmentCounters.CommitMatches==1,"paired native action observed");
 a.DefaultBehavior=AiBehavior.DefendSettlement;a.TargetSettlement=second;
 list=AiVisitSettlementBehavior.List();postfix.Invoke(null,new object[]{a,list});
 frame=new StrategicDecisionComposer.Frame{CandidateCount=2};
 HomeAssignmentLayer.Apply(a,think,frame);
 Check(list.Count==0&&frame.Scores.Count==0,"existing urgent native defense disables seam and policy");
 a.DefaultBehavior=AiBehavior.Other;
 think.AIBehaviorScores.Add(Tuple.Create(new AIBehaviorData{Party=second,AiBehavior=AiBehavior.DefendSettlement},0.1f));
 frame=new StrategicDecisionComposer.Frame{CandidateCount=3};HomeAssignmentLayer.Apply(a,think,frame);
 Check(frame.Scores.Count==0,"new legal urgent clan defense candidate preserves responsibility");
 think.AIBehaviorScores.RemoveAt(2);
 Clan.PlayerClan.FactionsAtWarWith.Add(new Clan());frame=new StrategicDecisionComposer.Frame{CandidateCount=2};
 HomeAssignmentLayer.Apply(a,think,frame);postfix.Invoke(null,new object[]{a,AiVisitSettlementBehavior.List()});
 Check(frame.Scores.Count==0&&!HomeAssignmentStore.Peace(a),"war contribution passthrough");Clan.PlayerClan.FactionsAtWarWith.Clear();
 home.OwnerClan=new Clan();Check(!HomeAssignmentStore.TryHome(a,out result)&&HomeAssignmentStore.CurrentHome(a.LeaderHero)==null,"foreign ownership invalidates immediately");
 Check(HomeAssignmentStore.TryHome(b,out result)&&result==second,"loss does not change another leader");
 Check(HomeAssignmentStore.Assign(a,second)&&HomeAssignmentStore.Clear("a")&&!HomeAssignmentStore.TryHome(a,out result),"runtime replacement/clear");
 HomeAssignmentStore.Records.Set("missinghero","missingsettlement");HomeAssignmentStore.ResolveLoaded();
 Check(!HomeAssignmentStore.Records.TryGet("missinghero",out var id),"missing references rejected on load");
 MBObjectManager.Instance.Objects["b"]=b.LeaderHero;MBObjectManager.Instance.Objects["castle_b"]=second;
 HomeAssignmentStore.Records.Set("b","castle_b");HomeAssignmentStore.BeginNewSession(true);
 Check(HomeAssignmentStore.TryHome(b,out result)&&result==second,"session restores cached identities");
 var recreated=Actor("b");recreated.LeaderHero=b.LeaderHero;b.LeaderHero.PartyBelongedTo=recreated;
 Check(HomeAssignmentStore.TryHome(recreated,out result)&&result==second,"party recreation retains hero identity");
 HomeAssignmentStore.BeginNewSession(false);Check(!HomeAssignmentStore.TryHome(recreated,out result),"new campaign resets static assignments");
 Console.WriteLine("TOTAL "+count+" PASS");
 }}
